#!/usr/bin/env kubectl apply -f
apiVersion: v1
kind: Service
metadata:
  name: htcondor-collector
  namespace: illume
  labels:
    name: htcondor-collector
spec:
  ports:
    - port: 9618
  selector:
    app: htcondor-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-collector
  namespace: illume
  labels:
    app: htcondor-collector
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: htcondor-collector
  template:
    metadata:
      labels:
        app: htcondor-collector
    spec:
      containers:
      - name: htcondor-collector
        image: illumecluster/htcondor-collector:latest
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "1000m"
          limits:
            memory: "1.0Gi"
            cpu: "1000m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-collector"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
          - name: pool-password
            mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/htcondor-collector-liveness
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-negotiator
  namespace: illume
  labels:
    app: htcondor-negotiator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: htcondor-negotiator
  template:
    metadata:
      labels:
        app: htcondor-negotiator
    spec:
      containers:
      - name: htcondor-negotiator
        image: illumecluster/htcondor-negotiator:latest
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "1000m"
          limits:
            memory: "1.0Gi"
            cpu: "1000m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-collector"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
          - name: pool-password
            mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
