# Implemented as a StatefulSet so we can have a volume mount per pod,
# since we want to have per-pod/per-worker scratch space.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: illume-work-gpu
  namespace: illume
spec:
  replicas: 1
  # we can handle parallel deployment
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: illume-work
      kind: gpu
  serviceName: "illume-work"
  template:
    metadata:
      labels:
        app: illume-work
        kind: gpu
      # we need this to make Singularity work: (more privileges)
      annotations:
        container.apparmor.security.beta.kubernetes.io/work: unconfined
    spec:
      containers:
      - name: work
        image: illumecluster/htcondor-worker:latest
        resources:
          requests:
            memory: "56Gi"    # 8GiB of memory per core
            cpu: "7"          # 7 CPU cores
            nvidia.com/gpu: 4 # request 4 GPUs (one CPU core per GPU)
          limits:
            memory: "56Gi"    # 8GiB of memory per core
            cpu: "7"          # 7 CPU cores
            nvidia.com/gpu: 4 # request 4 GPUs (one CPU core per GPU)
        # we need this to make Singularity work: (more privileges)
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
        env:
        - name: CONDOR_HOST
          value: "illume-coll"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        - name: CONDOR_SCRATCH
          value: "/scratch"
        - name: LDAP_SERVER
          value: "openldap.illume"
        - name: LDAP_BASEDN
          value: "dc=illume,dc=systems"
        # let condor know about out CPU and memory limits
        - name: CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: work
              resource: limits.cpu
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: work
              resource: limits.memory
        volumeMounts:
          - name: pool-password
            mountPath: /etc/condor/pool_password
          - name: homedir
            mountPath: /home
            subPath: illume/home
          - name: cvmfs
            mountPath: /cvmfs
          - name: scratch
            mountPath: /scratch
        ports:
        - containerPort: 9618
          protocol: TCP
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
      - name: homedir
        nfs:
          server: 192.168.19.2
          path: "/mnt/tank/export/scratch/icecube"
      - name: cvmfs
        hostPath:
          path: "/cvmfs"
      - name: scratch
        emptyDir:
          sizeLimit: 700Gi
