#- name: download rke
#  get_url:
#    url: https://github.com/rancher/rke/releases/download/v0.1.1/rke
#    checksum: sha256:00d91bd75e8b68c986fa229eee9606f8f1e69a134a64f02b162d20deb44f3381
#    dest: /usr/local/bin/rke
#    mode: 0555
#  become: true

- name: check out rke from github
  git:
    repo: 'https://github.com/rancher/rke'
    dest: /home/{{ ansible_user }}/rke

- name: install make
  apt:
    name: make
  become: true

- name: build rke
  make:
    chdir: /home/{{ ansible_user }}/rke
  async: 1000
  poll: 10

- name: install rke binary
  copy:
    src: /home/{{ ansible_user }}/rke/bin/rke
    dest: /usr/local/bin/rke
    mode: 0555
    owner: root
    group: root
    remote_src: yes
  become: true

- name: install cluster.yml
  copy:
    src: ../files/cluster.yml
    dest: "/home/{{ ansible_user }}/cluster.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"
    force: yes
    backup: yes

- name: install nvidia-device-plugin.yml
  copy:
    src: ../files/nvidia-device-plugin.yml
    dest: "/home/{{ ansible_user }}/nvidia-device-plugin.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"

- name: install example-ubuntu-host.yml
  copy:
    src: ../files/example-ubuntu-host.yml
    dest: "/home/{{ ansible_user }}/example-ubuntu-host.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"

- meta: flush_handlers
