#- name: download rke
#  get_url:
#    url: https://github.com/rancher/rke/releases/download/v0.1.1/rke
#    checksum: sha256:00d91bd75e8b68c986fa229eee9606f8f1e69a134a64f02b162d20deb44f3381
#    dest: /usr/local/bin/rke
#    mode: 0555
#  become: true

- name: check out rke from github
  git:
    repo: 'https://github.com/rancher/rke'
    dest: /home/{{ ansible_user }}/rke

- name: install make
  apt:
    name: make
  become: true

- name: build rke
  make:
    chdir: /home/{{ ansible_user }}/rke
  async: 1000
  poll: 10

- name: install rke binary
  copy:
    src: /home/{{ ansible_user }}/rke/bin/rke
    dest: /usr/local/bin/rke
    mode: 0555
    owner: root
    group: root
    remote_src: yes
  become: true

- name: install cluster.yml
  copy:
    src: ../files/cluster.yml
    dest: "/home/{{ ansible_user }}/cluster.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rw,g=r,o=r"
    force: yes
    backup: yes

- name: install kubernetes setup files
  copy:
    src: "../files/{{ item.name }}"
    dest: "/home/{{ ansible_user }}/{{ item.name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: '00_rke_up.sh', mode: 'u=rwx,g=rx,o=rx' }
    - { name: '02_nvidia-device-plugin.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '04_label_kube-system_namespace.sh', mode: 'u=rwx,g=rx,o=rx' }
    - { name: '05_illume-namespace.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '06_allow-namespace-illume.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '07_allow-dns-access.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '08_allow-public-internet.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '09_rook-operator.yaml', mode: 'u=rw,g=r,o=r' }
    - { name: '10_wait_for_operator.sh', mode: 'u=rwx,g=rx,o=rx' }
    - { name: '12_rook-cluster.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '13_wait_for_rook-cluster.sh', mode: 'u=rwx,g=rx,o=rx' }
    - { name: '14_storage_pool_and_class.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '15_rook-tools.yml', mode: 'u=rw,g=r,o=r' }
    - { name: '16_example-ubuntu-host.yml', mode: 'u=rw,g=r,o=r' }

- name: install kubernetes setup file templates
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ ansible_user }}/{{ item.name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: '01_taint_control_nodes.sh', mode: 'u=rwx,g=rx,o=rx' }
    - { name: '03_taint_gpu_nodes.sh', mode: 'u=rwx,g=rx,o=rx' }
    - { name: '11_label_storage_nodes.yml', mode: 'u=rw,g=r,o=r' }

- meta: flush_handlers
