---
- hosts: all
  roles:
    - common

- hosts: proxy
  roles:
    - squid

- hosts: worker-gpu:worker-nogpu:ingress
  roles:
    - cvmfs
    - zerotier

- hosts: worker-gpu
  roles:
    - cuda
    - nvidia-docker

- hosts: bastion
  roles:
    - rke

# abort here in case of any errors
- hosts: all
  any_errors_fatal: true
