---
- hosts: all
  roles:
    - common

- hosts: worker-gpu:worker-nogpu:ingress
  roles:
    - zerotier

- hosts: worker-gpu
  roles:
    - cuda
    - nvidia-docker

- hosts: bastion
  roles:
    - rke
