---
- hosts: all
  roles:
    - common

# set up the proxies
- hosts: proxy
  roles:
    - squid

# docker on everything but the proxy hosts
- hosts: all:!proxy
  roles:
    - docker

# workers need cvmfs and zerotier
- hosts: worker-gpu:worker-nogpu:ingress
  roles:
    - cvmfs
    - zerotier

# GPU workers need cuda and nvidia-docker
- hosts: worker-gpu
  roles:
    - cuda
    - nvidia-docker

# and the bastion host needs rke so we can deploy kubernetes
- hosts: bastion
  roles:
    - rke

# abort here in case of any errors
- hosts: all
  any_errors_fatal: true
